spring:
  cloud:
    gateway:
      routes:
      - id: ms-productos
        uri: lb://ms-productos
        predicates:
        - Path=/api/productos/**
        filters:
        - StripPrefix=0
        - name: Cookie
          args:
            message: mensaje personalizo
            name: user
            value: javier
      - id: ms-items
        uri: lb://ms-items
        predicates:
        - Path=/api/item/**
        filters:
        - StripPrefix=0
        - AddRequestHeader=token-request,sasdfsafas
        - AddResponseHeader=token-response, 1354567
        - AddRequestParameter=name, Felipe
        - SetResponseHeader=Content-Type, application/json
        - name: Cookie
          args:
            message: mensaje personalizo
            name: user
            value: jesus
